</head>
<body>
	<div id="header">
		<div class="head">
		   <ul class="nav">
		      <li><a href="http://ldp.showgames.cn/index.jsp" title="index"><span class="title_head"></span><span class="title">首页</span></a></li>
		      <li><a href="http://ldp.showgames.cn/download.jsp" title="baike"><span class="title_head"></span><span class="title">下载专区</span></a></li>
		      <li><a href="http://ldp.showgames.cn/material.jsp" title="health"><span class="title_head"></span><span class="title">游戏资料</span></a></li>
		      <li><a href="http://ldpbbs.showgames.cn/forum.php" title="circum"><span class="title_head"></span><span class="title">游戏论坛</span></a></li>
		      <li><a href="" title="shopping"><span class="title_head"></span><span class="title">关于</span></a></li>
		      <!-- <li id="more">
			    <a href="http://www.haowenjiao.com/examples/">
				  <span class="title_head"></span>
				  <span class="title more"><span>更多</span><span class="gbma"></span></span>
			    </a>
			    <div id="more_div">
				  <div style="padding:10px 0">
					<div><a href="http://www.haowenjiao.com/?topic=news" onclick="location.href='http://www.haowenjiao.com/?topic=news'"><span>新闻</span></a></div>
					<div><a href="http://www.haowenjiao.com/examples/" onclick="location.href='http://www.haowenjiao.com/examples/'"><span>更多 &gt;&gt;</span></a></div>
				  </div>
			    </div>
		      </li>       -->
		   </ul>
		</div>
		</div>
		<div id="logo" class="wtcenter"><h1>管理平台</h1></div>
		<style type="text/css">
		#login{position:absolute;top:0px;right:0px;background-color:#222;width:82px;height:30px;font-size:13px;overflow:hidden;}

		#login a{color:#747474;display: inline-block;padding-top:2px;}
		#login a:hover{background-color:#4c4c4c;display:inline-block;padding-top:2px;}
		#login a .title {padding:0 5px;z-index:1000;color:#CCC;line-height:27px;}
		</style>
		<div id="login">
		      <a href="/userLogin/userLogin.yaws"><span class="title">登录</span></a>
		      <a href="/userLogin/reg.yaws"><span class="title">注册</span></a>
		</div>