<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" type="text/css" href="/css/public.css" />
<script type="text/javascript" src="/lib/jquery.min.js"></script>
<script type="text/javascript" src="/js/public.js"></script>
<script type="text/javascript" src="/lib/flot/jquery.flot.js"></script>
<script type="text/javascript" src="/lib/flot/jquery.flot.categories.min.js"></script>
