<div id="sidePanel">
	<ul>
		<li class="selected" data="gm_1.yaws"><p>角色信息管理</p></li> 
		<li data="gm_2.yaws"><p>道具消耗</p></li>
		<li data="gm_3.yaws"><p>充值记录</p></li>
		<li data="gm_4.yaws"><p>元宝消耗</p></li>
		<li data="gm_5.yaws"><p>邮件管理</p></li>
		<li data="gm_6.yaws"><p>全服公告</p></li>
		<li data="gm_7.yaws"><p>游戏公告</p></li>
		<li data="gm_8.yaws"><p>服务器总览</p></li>
		<li data="gm_9.yaws"><p>bug反馈</p></li>
		<li data="gm_10.yaws"><p>封禁查询</p></li>
		<li data="gm_11.yaws"><p>推送</p></li>
	</ul>
</div>	